<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><i class="fa fa-dashboard fa-fw"></i> Добавить операцию</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php
        // Создаём заголовок страницы, который загрузится в layout
        $this->headTitle("Добавить операцию");
        // Выводим форму, полученную из контроллера
        echo $this->form;
        ?>
    </div>
</div>