<?php $kurs = Zend_Registry::getInstance(); ?>
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>

        <meta charset="windows-1251">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>iLevel test</title>

        <link rel="shortcut icon" href="/img/icon.png">
        <!--Bootstrap Core CSS--> 
        <link href="/css/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

        <!--MetisMenu CSS--> 
        <!--<link href="/css/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">-->

        <!--Timeline CSS--> 
        <!--<link href="/css/dist/css/timeline.css" rel="stylesheet">-->

        <!--Morris Charts CSS--> 
        <!--<link href="/css/bower_components/morrisjs/morris.css" rel="stylesheet">-->

        <!--Custom Fonts--> 
        <link href="/css/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!--Custom CSS--> 
        <link href="/css/dist/css/sb-admin-2.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">

        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
        
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.12.4.js"></script>
        <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">iLevel Money Diary test</a>
                    <span id="kurs" class="navbar-brand" rel="nodata">Текущий курс USD: <?=$kurs['kurs'][2]->buy?>/<?=$kurs['kurs'][2]->sale?> EUR:<?=$kurs['kurs'][0]->buy?>/<?=$kurs['kurs'][0]->sale?></span>
                </div>
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="<?php echo $this->url(array(), 'diary');  ?>"><i class="fa fa-dashboard fa-fw"></i> Дневник расходов</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array(), 'setup');  ?>"><i class="fa fa-magic fa-fw"></i> Настройки</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>
            <div id="page-wrapper">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>
        <!-- /#wrapper -->
    </body>

</html>
